[package]
name = "rust-httpserver"
version = "0.1.0"
edition = "2018"

[dependencies]
hyper = { version = "0.14.27", features = ["full"] }
tokio = { version = "1.32.0", features = ["full"] }
log = "0.4.20"
env_logger = "0.10.0"
